import Head from 'next/head';
import Link from 'next/link';
import { makeStyles } from 'tss-react/mui';

import Header from '../header/header';
import Screen from '../screen/screen.js';
import Keypad from '../keypad/keypad';

const useStyles = makeStyles()((theme) => {
  return {
    container: {
      padding: '0 2rem',
      position: 'relative',
      width: '100vw',
      height: '100vh',
      backgroundColor: `${theme.palette.primary.main}`,
      [theme.breakpoints.down('sm')]: {
        padding: '0 1.5rem',
      },
    },
    main: {
      height: '850px',
      width: '100%',
    },
    calculatorContainer: {
      position: 'relative',
      width: '100%',
      height: '100%',
    },
    calculatorFrame: {
      height: '710px',
      width: '540px',
      // border: '1px solid #fff',
      position: 'absolute',
      top: '67%',
      left: '50%',
      transform: 'translate(-50%, -67%)',
      [theme.breakpoints.down('sm')]: {
        width: '100%',
        height: '735px',
        top: '9%',
        left: '50%',
        transform: 'translate(-50%, -9%)',
      },
    },
    footer: {
      display: 'flex',
      flex: '1',
      width: 'calc(100% - 4rem)',
      position: 'absolute',
      padding: '1rem 0 0 0',
      bottom: '1rem',
      borderTop: `1px solid ${theme.palette.common.text_switch}`,
      justifyContent: 'center',
      alignItems: 'center',
      color: `${theme.palette.common.text_switch}`,
      [theme.breakpoints.down('sm')]: {
        fontSize: '0.65rem',
        padding: '0.5rem 0 0 0',
        width: 'calc(100% - 3rem)',
        bottom: '0.5rem',
      },
    },
    spacer: {
      width: '100%',
      padding: '0.7rem',
      [theme.breakpoints.down('sm')]: {
        padding: '0.8rem',
      },
    },
  };
});

function Calculator() {
  const { classes } = useStyles();
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={classes.main}>
        <div className={classes.calculatorContainer}>
          <div className={classes.calculatorFrame}>
            <Header />
            <div className={classes.spacer} />
            <Screen />
            <div className={classes.spacer} />
            <Keypad />
          </div>
        </div>
      </main>

      <footer className={classes.footer}>
        Challenge by&nbsp;
        <Link
          href='https://www.frontendmentor.io/challenges/calculator-app-9lteq5N29/hub'
          target='_blank'
        >
          Frontend Mentor
        </Link>
        . Coded by&nbsp;
        <Link href='https://untea-rocmu-it.herokuapp.com/' target='_blank'>
          Catalin Marius Untea
        </Link>
        .
      </footer>
    </div>
  );
}

export default Calculator;
